// Generated by CoffeeScript 1.8.0

/**
 *
 * Wrap each repository name in a link
 *
 */

(function() {
  $(function() {
    return $(".repository-name").each(function() {
      return $(this).wrap("<a href=\"http://github.com/alflanagan/" + this.textContent + "\"/>");
    });
  });

}).call(this);
